version: '3.8'

services:
  postgres:
    container_name: mapStore_postgres
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mapStore